### ISSUE TITLE
In function `llogit()` variable `path_of_report` throws an unused argument error

### ISSUE THREAD

**Issue by jn-goe** [vertesy/MarkdownHelpers#4]
Hi :) 
When I call the function `llogit()` the variable `path_of_report` throws an error, I guess this might happen because it is not defined before it is called in `ww.variable.and.path.exists(path_of_report = path_of_report)` ?

```
fname <- "vec...bar..pdf"
MarkdownHelpers::llogit(Stringendo::kollapse("![", file_name, "]", "(", file_name, ")", print = FALSE))
# Error in ww.variable.and.path.exists(path_of_report = path_of_report,  : 
# unused argument (path_of_report = path_of_report)
```

**Comment by vertesy** [comment]
Thanks!
This gonna be more a longer shot...

**Comment by vertesy** [comment]
So all of the `MarkdownHelpers` function write into a markdown file.
That is defined by first calling `MarkdownReports::setup_MarkdownReports()`

`MarkdownReports` works with background variables (defined in global env).

**Comment by vertesy** [comment]
TBH, you also may have an old version. `path_of_report = path_of_report` does not exist (before I was trying to debug yesterday).  
Without setup, it gives me the expected warning

```r
> llogit('assa')
NOT LOGGED: Log path and filename is not defined in path_of_report.
```
